controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    position_controller:
      type: position_controllers/JointGroupPositionController

positon_controller:
  ros__parameters:
    joints: 
      - joint_end_sphere

joint_state_broadcaster:
  ros__parameters:
    joints: 
      - joint_end_sphere